### ISSUE TITLE
i can't get the docker working at all need help  

### ISSUE THREAD

**Issue by jakefever191** [printfuck/stardew-multiplayer-docker#11]
this is the log from it 

Waiting for display

05/06/2021 13:30:34 passing arg to libvncserver: -rfbport

05/06/2021 13:30:34 passing arg to libvncserver: 5900

05/06/2021 13:30:34 passing arg to libvncserver: -rfbportv6

05/06/2021 13:30:34 passing arg to libvncserver: -1

05/06/2021 13:30:34 passing arg to libvncserver: -httpportv6

05/06/2021 13:30:34 passing arg to libvncserver: -1

05/06/2021 13:30:34 passing arg to libvncserver: -desktop

05/06/2021 13:30:34 passing arg to libvncserver: StardewValley

05/06/2021 13:30:34 passing arg to libvncserver: -passwd

05/06/2021 13:30:34 x11vnc version: 0.9.13 lastmod: 2011-08-10 pid: 29

05/06/2021 13:30:34 Using X display :10

05/06/2021 13:30:34 rootwin: 0x388 reswin: 0x200001 dpy: 0x7c638360

05/06/2021 13:30:34

05/06/2021 13:30:34 ------------------ USEFUL INFORMATION ------------------

05/06/2021 13:30:34 X DAMAGE available on display, using it for polling hints.

05/06/2021 13:30:34 To disable this behavior use: '-noxdamage'

05/06/2021 13:30:34

05/06/2021 13:30:34 Most compositing window managers like 'compiz' or 'beryl'

05/06/2021 13:30:34 cause X DAMAGE to fail, and so you may not see any screen

05/06/2021 13:30:34 updates via VNC. Either disable 'compiz' (recommended) or

05/06/2021 13:30:34 supply the x11vnc '-noxdamage' command line option.

05/06/2021 13:30:34

05/06/2021 13:30:34 Wireframing: -wireframe mode is in effect for window moves.

05/06/2021 13:30:34 If this yields undesired behavior (poor response, painting

05/06/2021 13:30:34 errors, etc) it may be disabled:

05/06/2021 13:30:34 - use '-nowf' to disable wireframing completely.

05/06/2021 13:30:34 - use '-nowcr' to disable the Copy Rectangle after the

05/06/2021 13:30:34 moved window is released in the new position.

05/06/2021 13:30:34 Also see the -help entry for tuning parameters.

05/06/2021 13:30:34 You can press 3 Alt_L's (Left "Alt" key) in a row to

05/06/2021 13:30:34 repaint the screen, also see the -fixscreen option for

05/06/2021 13:30:34 periodic repaints.

05/06/2021 13:30:34 GrabServer control via XTEST.

05/06/2021 13:30:34

05/06/2021 13:30:34 Scroll Detection: -scrollcopyrect mode is in effect to

05/06/2021 13:30:34 use RECORD extension to try to detect scrolling windows

05/06/2021 13:30:34 (induced by either user keystroke or mouse input).

05/06/2021 13:30:34 If this yields undesired behavior (poor response, painting

05/06/2021 13:30:34 errors, etc) it may be disabled via: '-noscr'

05/06/2021 13:30:34 Also see the -help entry for tuning parameters.

05/06/2021 13:30:34 You can press 3 Alt_L's (Left "Alt" key) in a row to

05/06/2021 13:30:34 repaint the screen, also see the -fixscreen option for

05/06/2021 13:30:34 periodic repaints.

05/06/2021 13:30:34

05/06/2021 13:30:34 XKEYBOARD: number of keysyms per keycode 7 is greater

05/06/2021 13:30:34 than 4 and 51 keysyms are mapped above 4.

05/06/2021 13:30:34 Automatically switching to -xkb mode.

05/06/2021 13:30:34 If this makes the key mapping worse you can

05/06/2021 13:30:34 disable it with the "-noxkb" option.

05/06/2021 13:30:34 Also, remember "-remap DEAD" for accenting characters.

05/06/2021 13:30:34

05/06/2021 13:30:34 X FBPM extension not supported.

Xlib: extension "DPMS" missing on display ":10".

05/06/2021 13:30:34 X display is not capable of DPMS.

05/06/2021 13:30:34 --------------------------------------------------------

05/06/2021 13:30:34

05/06/2021 13:30:34 Default visual ID: 0x21

05/06/2021 13:30:34 Read initial data from X display into framebuffer.

05/06/2021 13:30:34 initialize_screen: fb_depth/fb_bpp/fb_Bpl 24/32/6320

05/06/2021 13:30:34 *** unrecognized option(s) ***

05/06/2021 13:30:34 [1] 20

05/06/2021 13:30:34 For a list of options run: x11vnc -opts

05/06/2021 13:30:34 or for the full help: x11vnc -help

05/06/2021 13:30:34

05/06/2021 13:30:34 Here is a list of removed or obsolete options:

05/06/2021 13:30:34

05/06/2021 13:30:34 removed: -hints, -nohints

05/06/2021 13:30:34 removed: -cursorposall

05/06/2021 13:30:34 removed: -nofilexfer, now the default.

05/06/2021 13:30:34

05/06/2021 13:30:34 renamed: -old_copytile, use -onetile

05/06/2021 13:30:34 renamed: -mouse, use -cursor

05/06/2021 13:30:34 renamed: -mouseX, use -cursor X

05/06/2021 13:30:34 renamed: -X, use -cursor X

05/06/2021 13:30:34 renamed: -nomouse, use -nocursor

05/06/2021 13:30:34 renamed: -old_pointer, use -pointer_mode 1

command

/usr/bin/xterm

[libi3] ../../i3-wm-4.16.1/libi3/font.c Using Pango font monospace, size 8

[libi3] ../../i3-wm-4.16.1/libi3/font.c Using Pango font monospace, size 8

[libi3] ../../i3-wm-4.16.1/libi3/font.c Using Pango font monospace, size 8

/bin/sh: 1: i3status: Operation not permitted

[../../i3-wm-4.16.1/i3bar/src/child.c:468] ERROR: Child (pid: 75) unexpectedly exited with status 2

**Comment by printfuck** [comment]
Hi jake,

It seems, that you are trying to run an old version, which you probably have built some time ago. 
Try pulling the repo and rebuilding the docker container:
```
git pull
docker-compose build --no-cache
docker-compose down
docker-compose up -d
```

**Comment by jakefever191** [comment]
do i need a Linux copy of stardew or is that in the github pull

**Comment by jakefever191** [comment]
can i add other mods? to it

**Comment by printfuck** [comment]
Yes, you can. I think the easiest way would be adding the mod folder (which you would usually put into the `Mods` folder within the Stardew Valley game folder) via volume mount like this:
```
    ...
    volumes:
      - ./MYMOD:/data/Stardew/Stardew Valley/Mods/MYMOD
```
In this case the `MYMOD` folder is in the same directory as the `docker-compose.yml` file
