### ISSUE TITLE
Windows git client sent me down a rabbithole

### ISSUE THREAD

**Issue by apdastous** [printfuck/stardew-multiplayer-docker#13]
I cloned this repo in my windows environment, which converted line endings to windows style... but of course we want these scripts to run inside the unix based docker container.  For a while I couldn't tell what was wrong until I made a bash entrypoint and actually examined startapp.sh and the scripts in /opt.  I have a work in progress branch that simply adds dos2unix to the image and runs a few extra steps on the container, is there any interest in me putting up a PR?

**Comment by printfuck** [comment]
Hi there,

Sorry, for the long waiting time and thanks for your work and effort.

I'd really like to look into your changes, and most likely would accept your PR.
