### ISSUE TITLE
Server out of date

### ISSUE THREAD

**Issue by pioneer898** [printfuck/stardew-multiplayer-docker#14]
The hosted server tar.gz is out of date with the current version of SV. I don't mind hosting my own, but the vanilla download doesn't seem to have the right files. Do you have a process for creating your hosted Stardew_latest.tar.gz content that you could share?

**Comment by printfuck** [comment]
Oh, yeah...

I tried to automate the new SMAPI installer. I hate it || :

Thanks for the issue :smiley:

**Comment by AkumaNoYami** [comment]
@printfuck  can you Add the Mod Stardew Valley Expanded?
