### ISSUE TITLE
Questions for UnRaid Setup

### ISSUE THREAD

**Issue by mihcox** [printfuck/stardew-multiplayer-docker#16]
I am trying to configure this on unRaid, and many of your guidances say "You can control the ... with environment variables in the docker-compose.yml file."

Do you have a description of what variables are in the docker-compose file, or could be added. I would like to apply a save game I already have, but am not sure how to pass in the parameter. Also, how could I edit the "config.json" file as I do not see anywhere on the system the data is written?

**Comment by printfuck** [comment]
Hi there,

If you haven't solved your problem yet, I hope, that the following will be helpful:

Let's say, you're Savegame is called `DystopiaNow_38495334`. Last time I looked, savegame folders had this kind of naming scheme. This folder you'd put - for example - inside of `/data/docker/stardew/saves`.

In the `docker-compose.yml` file, you would now have to edit the volumes section like so:
```
 volumes:
      # Saves go here now
      - /data/docker/stardew/saves:/config/xdg/config/StardewValley/Saves
      ...  
``` 
Now, you could start the container and select your savegame from the menu. Once you load (start) the savegame, the autoload mod should make sure, that on every restart the same savegame will be continued.

You could also edit the `autoload.json` and enter your savegame's name like this:
```
{
  "LastFileLoaded": "DystopiaNow_38495334",
  "LoadIntoMultiplayer": true,
  "ForgetLastFileOnTitle": true
}
```
Given, your edited config is placed at `/data/docker/stardew/autoload.json`, you again would have to mount that file into the container via:
```
 volumes:
      ...
      # The stateful configs should be initially empty files with 777 permission
      - /data/docker/stardew/autoload.json:/data/Stardew/Stardew Valley/Mods/AutoLoadGame/config.json
```
Also make sure it's readable and writable ( for example with `chmod 777 /data/docker/stardew/autoload.json`)
