### ISSUE TITLE
Any advice on updating the game files?

### ISSUE THREAD

**Issue by Fungusware** [printfuck/stardew-multiplayer-docker#20]
I'd like to update to 1.5.6, can anyone give me tips how to do so. I have the games files for windows but not sure where to copy them.

**Comment by printfuck** [comment]
The container should deliver the most recent version 1.5.6. Updating your game works via Steam.

If you'd like to replace the game files inside the container, you'd have to rewrite the Dockerfile to fetch a tar'ed version of the game files inside your the `steamapps`-Folder  on a linux installation.

https://github.com/printfuck/stardew-multiplayer-docker/blob/29f10f2155a44117c8b8a265f1d58235e28b3033/docker/Dockerfile#L12-L17

You might delete Line 15 and write before Line 13 something like `ADD Stardew.tar.gz /data/latest.tar.gz` assuming you tar'ed and gzip'ed the the game files as explained to a file named `Stardew.tar.gz` in the same directory as the Dockerfile.

**Comment by Fungusware** [comment]
Thanks for the info. The games files seem to be 1.5.5, but I guess thats cause I used a container from Docker Hub.

I'll play around with building myself. 

Regards
