### ISSUE TITLE
Host account trigger commands?

### ISSUE THREAD

**Issue by w4sb0y** [printfuck/stardew-multiplayer-docker#25]
I don't know what mod is this pack using for this, but is there, or can be implemented a feature where you type in a command to trigger the automated host to do? Like when there's the egg festival, if we type /skip /go or !skip !go and the event is started by the host/admin/owner player?

**Comment by HumanoidSandvichDispenser** [comment]
I believe the Always On Server mod, which is included in this repository, has the chat commands `!festival` and `!event` to manually trigger festivals and event cutscenes.

[Here is the mod homepage](https://www.nexusmods.com/stardewvalley/mods/2677) if you need more mod documentation.
