### ISSUE TITLE
How can I use my own legitimate game as the host?

### ISSUE THREAD

**Issue by 0Vessel0** [printfuck/stardew-multiplayer-docker#28]
>The game will be pulled from my servers

I'm sorry but I can't understand this. Did the game files come from your Steam account, or using a pirated version of the game? If it's the former, would using this Docker container interfere with your gameplay? I have more than one Steam account and this game. By using Steam, I can use services like cloud saves. So, if I want to use a legitimate game purchased on Steam as the host, how should I modify the Dockerfile?

**Comment by dimaguy** [comment]
You need to make it so something like DepotDownloader or SteamCMD is used to download the latest version from steam and then execute from there, cloud saves will likely not be available even with this, as a steam runtime needs to run to sync them

**Comment by 0Vessel0** [comment]
> You need to make it so something like DepotDownloader or SteamCMD is used to download the latest version from steam and then execute from there, cloud saves will likely not be available even with this, as a steam runtime needs to run to sync them
> 
> P.S.: the current way that's being done is very much illegal as the author does not have authorization to redistribute files

Thx bro.I finally gave up on this docker and started my server using steamcmd and the desktop environment.And I'll close this issue.
