### ISSUE TITLE
unable to bring it up

### ISSUE THREAD

**Issue by yugioh** [printfuck/stardew-multiplayer-docker#3]
tried using docker compose and ansible-localhost. it fails to come up

valley_1  | 25/03/2020 17:59:53 x11vnc version: 0.9.13 lastmod: 2011-08-10  pid: 24
valley_1  | 25/03/2020 17:59:53 XOpenDisplay(":10") failed.
valley_1  | 25/03/2020 17:59:53 Trying again with XAUTHLOCALHOSTNAME=localhost ...
valley_1  |
valley_1  | 25/03/2020 17:59:53 ***************************************
valley_1  | 25/03/2020 17:59:53 *** XOpenDisplay failed (:10)
valley_1  |
valley_1  | *** x11vnc was unable to open the X DISPLAY: ":10", it cannot continue.
valley_1  | *** There may be "Xlib:" error messages above with details about the failure.
valley_1  |
valley_1  | Some tips and guidelines:
valley_1  |
valley_1  | ** An X server (the one you wish to view) must be running before x11vnc is
valley_1  |    started: x11vnc does not start the X server.  (however, see the -create
valley_1  |    option if that is what you really want).
valley_1  |
valley_1  | ** You must use -display <disp>, -OR- set and export your $DISPLAY
valley_1  |    environment variable to refer to the display of the desired X server.
valley_1  |  - Usually the display is simply ":0" (in fact x11vnc uses this if you forget
valley_1  |    to specify it), but in some multi-user situations it could be ":1", ":2",
valley_1  |    or even ":137".  Ask your administrator or a guru if you are having
valley_1  |    difficulty determining what your X DISPLAY is.
valley_1  |
valley_1  | ** Next, you need to have sufficient permissions (Xauthority)
valley_1  |    to connect to the X DISPLAY.   Here are some Tips:
valley_1  |
valley_1  |  - Often, you just need to run x11vnc as the user logged into the X session.
valley_1  |    So make sure to be that user when you type x11vnc.
valley_1  |  - Being root is usually not enough because the incorrect MIT-MAGIC-COOKIE
valley_1  |    file may be accessed.  The cookie file contains the secret key that
valley_1  |    allows x11vnc to connect to the desired X DISPLAY.
valley_1  |  - You can explicitly indicate which MIT-MAGIC-COOKIE file should be used
valley_1  |    by the -auth option, e.g.:
valley_1  |        x11vnc -auth /home/someuser/.Xauthority -display :0
valley_1  |        x11vnc -auth /tmp/.gdmzndVlR -display :0
valley_1  |    you must have read permission for the auth file.
valley_1  |    See also '-auth guess' and '-findauth' discussed below.
valley_1  |
valley_1  | ** If NO ONE is logged into an X session yet, but there is a greeter login
valley_1  |    program like "gdm", "kdm", "xdm", or "dtlogin" running, you will need
valley_1  |    to find and use the raw display manager MIT-MAGIC-COOKIE file.
valley_1  |    Some examples for various display managers:
valley_1  |
valley_1  |      gdm:     -auth /var/gdm/:0.Xauth
valley_1  |               -auth /var/lib/gdm/:0.Xauth
valley_1  |      kdm:     -auth /var/lib/kdm/A:0-crWk72
valley_1  |               -auth /var/run/xauth/A:0-crWk72
valley_1  |      xdm:     -auth /var/lib/xdm/authdir/authfiles/A:0-XQvaJk
valley_1  |      dtlogin: -auth /var/dt/A:0-UgaaXa
valley_1  |
valley_1  |    Sometimes the command "ps wwwwaux | grep auth" can reveal the file location.
valley_1  |
valley_1  |    Starting with x11vnc 0.9.9 you can have it try to guess by using:
valley_1  |
valley_1  |               -auth guess
valley_1  |
valley_1  |    (see also the x11vnc -findauth option.)
valley_1  |
valley_1  |    Only root will have read permission for the file, and so x11vnc must be run
valley_1  |    as root (or copy it).  The random characters in the filenames will of course
valley_1  |    change and the directory the cookie file resides in is system dependent.
valley_1  |
valley_1  | See also: http://www.karlrunge.com/x11vnc/faq.html
valley_1  |
valley_1  |  --- x11vnc loop: sleeping 2000 ms ---
valley_1  |
valley_1  | command
valley_1  | /usr/bin/xterm
valley_1  | i3: Cannot open display
valley_1  |
valley_1  | Warning: This program is an suid-root program or is being run by the root user.
valley_1  | The full text of the error or warning message cannot be safely formatted
valley_1  | in this environment. You may get a more descriptive message by running the
valley_1  | program as a non-root user or by removing the suid bit on the executable.
valley_1  | xterm: Xt error: Can't open display: %s

**Comment by addy3494** [comment]
weird

the playbook brings up the container momentarily 

ok: [ubp]

TASK [Start docker-compose] **************************************************************************************************************************************************************changed: [ubp]

PLAY RECAP *******************************************************************************************************************************************************************************ubp                        : ok=24   changed=1    unreachable=0    failed=0

__________________________________________________________


minecraft@ubp:~$ docker ps
CONTAINER ID        IMAGE               COMMAND              CREATED             STATUS              PORTS                                              NAMES
f2f7b9151a11        stardew_valley      "/bin/sh /init.sh"   27 minutes ago      Up 1 second         0.0.0.0:24642->24642/udp, 0.0.0.0:5902->5900/tcp   stardew_valley_1
minecraft@ubp:~$ docker exec -it f2f7b9151a11 bash
Error response from daemon: Container f2f7b9151a112db1f16b9a66fbce2fd5bb0dec50ec1207d8ccc9004326dc5ae3 is not running
minecraft@ubp:~$ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
minecraft@ubp:~$


any idea how i can debug this ?

**Comment by stockmind** [comment]
Forked and updated to support 1.4 with a GOG Linux installer 
https://github.com/stockmind/stardew-multiplayer-docker

I had your problem the first time I launched this repository and it seems that you need to grant NET_ADMIN privileges for i3

https://github.com/stockmind/stardew-multiplayer-docker/commit/1717c03389f596e5b1e2d6cb079036ad99371334

**Comment by addy3494** [comment]
Yeah im able to bring it up, how can connect my session it it ? its unable to find it.

**Comment by stockmind** [comment]
Please be more specific. What you've tried?
You added the network cap to this repository then Launcher?
You used my fork?
Have you connected with a vnc client to the server instance and loaded your save/created One from there?
I've some steps to follow on my README 
https://github.com/stockmind/stardew-multiplayer-docker/blob/master/README.md#launch-your-server

**Comment by printfuck** [comment]
There was a problem with the XSession lock file in /tmp/.X10-lock. This probably could have been the issue. But since this project were just some crude hacks from the beginning, there will always be flaws like that.

Anyway... For now this should be fixed.

**Comment by addy3494** [comment]
Yeah, this can be closed. there will always be issues and that is understandable, All i managed was to bring the container up. stopped playing the game anyway :) cheers !!
