### ISSUE TITLE
Loading other mods

### ISSUE THREAD

**Issue by iggycreates** [printfuck/stardew-multiplayer-docker#30]
Thanks for this docker! I am trying to add my own mods into the mods folder, but it only loads the default mods you put. How can I add my own mods?

**Comment by HumanoidSandvichDispenser** [comment]
You can add your mods to the `docker/mods` directory and rebuild the container. Then add an env variable to the compose file. The name of the variable should be `ENABLE_` + mod name, allcaps no spaces. For example, `docker/mods/Tractor Mod` -> `ENABLE_TRACTORMOD=true`.

**Comment by iggycreates** [comment]
I’ll try thanks!
