### ISSUE TITLE
Service 'valley' failed to build

### ISSUE THREAD

**Issue by fransole** [printfuck/stardew-multiplayer-docker#31]
Hello,

I've been trying to get this docker container to work however during the build process I'm getting the following error:

`---> Running in 961ad92c402a
The command '/bin/sh -c mkdir -p /data/Stardew &&     mkdir -p /data/nexus &&     wget https://eris.cc/Stardew_latest.tar.gz -qO /data/latest.tar.gz &&     tar xf /data/latest.tar.gz -C /data/Stardew &&     rm /data/latest.tar.gz'returned a non-zero code: 4
ERROR: Service 'valley' failed to build : Build failed`

Any ideas?

Looks like it's having trouble wget'ing the file from eris.cc although I can download the file in a browser.

Temp-fix:
Downloaded file, scp to host. cp file to docker/
Edited docker/Dockerfile to the following:

`# Game + ModLoader 1.5.6 3.18.2
RUN mkdir -p /data/Stardew && \
mkdir -p /data/nexus
COPY latest.tar.gz /data/latest.tar.gz
RUN tar xf /data/latest.tar.gz -C /data/Stardew && \
rm /data/latest.tar.gz`

**Comment by printfuck** [comment]
Thanks for the issue and especcially thanks for providing a solution! The return code 4 is most likely a result of wget failing to download the file due to me temporarily messing up the files on the server. 

Sorry for the inconvenience.
