### ISSUE TITLE
Cant connect to VNC, or Web Player

### ISSUE THREAD

**Issue by DragonDev07** [printfuck/stardew-multiplayer-docker#32]
Ran the server, it built fine, however when I attempt to connect to the VNC or Webserver, via either localhost or LAN, nothing happens. In both cases it just says "Refused connection" or something along those lines. When I run docker log <container>, the latest log is always 

`[<time> TRACE game] Disconnected: ServerOfflineMode]`

Any ideas for a fix anyone?

**Comment by sarahjaneweaver** [comment]
The port mappings in the docker-compose, don't match the ports selected when the vnc server is started.  Try the following ports instead (docker-compose.yml):

    ports:
      # VNC
      - 5900:5900
      # NOVNC WEB
      - 5800:5800
      # Game  
      - 24642:24642/udp
