### ISSUE TITLE
New update is coming, what should we do?

### ISSUE THREAD

**Issue by baolatui** [printfuck/stardew-multiplayer-docker#34]
Hi, as announced on the game homepage, a new update is coming with a lot of changes.
Do we need to do anything to make server run with latest update?

**Comment by briggsyj** [comment]
Hope the game `Stardew_latest.tar.gz` being pulled from the server is updated and mods don't break for thenew version.

**Comment by norimicry** [comment]
> Hope the game `Stardew_latest.tar.gz` being pulled from the server is updated and mods don't break for the new version. 

Did not look updated as of yet from what I could tell by looking at the game files. Submitted #35 to update game files.

**Comment by norimicry** [comment]
Assuming the author no longer upkeeps this repo. Currently working on a fork for 1.6 though it introduced a change in file structure and mod incompatibility. So far I have it running stable with the new changes and workaround mods, just need to find a good place to host the game files to pull from. Will update here when I have it finished.

**Comment by baolatui** [comment]
hi, I can help you with that, you can send me a description to my email: baolatui@gmail.com

**Comment by norimicry** [comment]
For all curious, see my fork here for a working 1.6 version: 

https://github.com/norimicry/stardew-multiplayer-docker

I have removed some of the bloated, deprecated code as well.

**Comment by printfuck** [comment]
Thanks @norimicry for your work. I will put a notice in the Readme linking to your repository for the case, that I can't keep up with the updates (If you're ok with that)

**Comment by norimicry** [comment]
@printfuck works for me.
