### ISSUE TITLE
ERROR: Service 'valley' failed to build

### ISSUE THREAD

**Issue by Alexmod** [printfuck/stardew-multiplayer-docker#38]
Hi!
After the command
`docker-compose up`
I get an error
`
curl: (6) Could not resolve host: stardewcommunitywiki.com
ERROR: Service 'valley' failed to build: The command '/bin/sh -c APP_ICON_URL=https://stardewcommunitywiki.com/mediawiki/images/4/48/Fiddlehead_Fern.png &&     install_app_icon.sh "$APP_ICON_URL"' returned a non-zero code: 6`

**Comment by printfuck** [comment]
Thanks for finding giving a solution @makeevrserg 😃 

The issue should be fixed by now.
