### ISSUE TITLE
ERROR [valley  4/14] RUN APP_ICON_URL=https://stardewvalleywiki.com/mediawiki/images/4/48/Fiddlehead_Fern.png 

### ISSUE THREAD

**Issue by krasnabiotech** [printfuck/stardew-multiplayer-docker#39]
Some error happened during generating favicons, it looks quite thorny. Is there anyone who can help me fix it?
It said the module 'node:stream' cannot be found. I swear I just use the original docker-compose file to build the docker, and just modify the APP_ICON_URL that is mentioned in the previous issue.

27.83 Generating favicons...
28.48 internal/modules/cjs/loader.js:818
28.48   throw err;
28.48   ^
28.48 
28.48 Error: Cannot find module 'node:stream'
28.48 Require stack:
28.48 - /tmp/cli-real-favicon/node_modules/parse5-parser-stream/dist/cjs/index.js
28.48 - /tmp/cli-real-favicon/node_modules/cheerio/dist/commonjs/index.js
28.48 - /tmp/cli-real-favicon/node_modules/metaparser/index.js
28.48 - /tmp/cli-real-favicon/node_modules/rfg-api/index.js
28.48 - /tmp/cli-real-favicon/node_modules/cli-real-favicon/real-favicon-generate.js
28.48     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
28.48     at Function.Module._load (internal/modules/cjs/loader.js:667:27)
28.48     at Module.require (internal/modules/cjs/loader.js:887:19)
28.48     at require (internal/modules/cjs/helpers.js:74:18)
28.48     at Object.<anonymous> (/tmp/cli-real-favicon/node_modules/parse5-parser-stream/dist/cjs/index.js:4:23)
28.48     at Module._compile (internal/modules/cjs/loader.js:999:30)
28.48     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
28.48     at Module.load (internal/modules/cjs/loader.js:863:32)
28.48     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
28.48     at Module.require (internal/modules/cjs/loader.js:887:19) {
28.48   code: 'MODULE_NOT_FOUND',
28.48   requireStack: [
28.48     '/tmp/cli-real-favicon/node_modules/parse5-parser-stream/dist/cjs/index.js',
28.48     '/tmp/cli-real-favicon/node_modules/cheerio/dist/commonjs/index.js',
28.48     '/tmp/cli-real-favicon/node_modules/metaparser/index.js',
28.48     '/tmp/cli-real-favicon/node_modules/rfg-api/index.js',
28.48     '/tmp/cli-real-favicon/node_modules/cli-real-favicon/real-favicon-generate.js'
28.48   ]
28.48 }
28.54 jq: error: Could not open file faviconData.json: No such file or directory
------
failed to solve: process "/bin/sh -c APP_ICON_URL=https://stardewvalleywiki.com/mediawiki/images/4/48/Fiddlehead_Fern.png &&     install_app_icon.sh \"$APP_ICON_URL\"" did not complete successfully: exit code: 2

**Comment by OlegYurchik** [comment]
Up
I have same issue

**Comment by chocolatescode** [comment]
This issue can be fixed when comment this 2 lines in Dockerfile: RUN APP_ICON_URL=https://www.stardewvalleywiki.com/mediawiki/images/3/33/Stardew_Checkup_Icon.png && \
    install_app_icon.sh "$APP_ICON_URL"
When you pulled repo you need cd docker and edit DockerFile

**Comment by printfuck** [comment]
I removed the lines from the Dockerfile, sorry for the inconvenience.
