### ISSUE TITLE
Cant Join Server

### ISSUE THREAD

**Issue by Ibnuard** [printfuck/stardew-multiplayer-docker#40]
Hi, i aready setup the server and docker and i can test the vnc too, but i cannot join to the server

i join co-op > join LAN game and input IP:24642 but always connection fail

i already do ufw allow 24642 also an open port on vps security group

**Comment by Tommiiee** [comment]
To Join: 
Co-Op > Join LAN Game... > <IP-Address without port>

Let me know if that helps.

**Comment by Ibnuard** [comment]
sorry thats my bad, i forgot to open udp port on vps settings, but i have another problem sometimes when 2 player join then the server will hang and not responding, my server spec is 2 core cpu and 4gb ram
