### ISSUE TITLE
Update Stardew valley to 1.5.2

### ISSUE THREAD

**Issue by mari0theminer** [printfuck/stardew-multiplayer-docker#6]
hey, love the project <3.

when i enter VNC this error message appears 
![image](https://user-images.githubusercontent.com/48063769/104656713-0a36b880-56c0-11eb-9d9b-160e936b3e01.png)

**Comment by rhohls** [comment]
Same issue. 
I managed to resolve myself temporarily by copying over the latest game files and overwriting the ones in the container

**Comment by mari0theminer** [comment]
> Same issue. 
> I managed to resolve myself temporarily by copying over the latest game files and overwriting the ones in the container 

Oh okay thx that's a good tip.

**Comment by printfuck** [comment]
I'm uploading the most recent version now. I'm glad you found out, how it works.
