### ISSUE TITLE
Poor screen resolution in VNC

### ISSUE THREAD

**Issue by fredmnl** [printfuck/stardew-multiplayer-docker#7]
When I first loaded the server through the web UI, the menu was displaying incorrectly, some options were outside the frame, some buttons overlapped etc ... 

Fixed it by using 1600x1280 resolution in the docker-compose environment variable but that might not be the most universal option. Should it become the default?

**Comment by printfuck** [comment]
The value was chosen after load testing. It seems to have a small impact on overall load though.

Since it is a docker-compose variable, it's supposed to be changed at some point.
